Gally\VectorSearch\Entity\VectorConfiguration:
    vector_config1:
        id: <findSourceFieldIdByCode('product', 'name')>
        sourceField: <findSourceFieldByCode('product', 'name')>
        isVectorisable: true
        position: 1
        prompt: "The product name is %s"
